[package]
name = "wpass"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
rufi = { version = "0.1", git = "https://github.com/icewind1991/rufi" }
main_error = "0.1.0"
glob = "0.3.0"
dirs = "2.0.2"